### ISSUE TITLE
SemVer default constructor arguments

### ISSUE THREAD

**Issue by NorbertSandor** [swiftzer/semver#15]
Wouldn't it be more logical to remove the default value at least in case of `major`?

```
    val major: Int,
    val minor: Int = 0,
    ...
```

I cannot think of a good use case for a constant "zero" version number...

**Comment by ericksli** [comment]
This is a breaking change and thus needs to wait until v2.0 (i.e. together with multiplatform support)

**Comment by ericksli** [comment]
You can see the code change in `multiplatform` branch

**Comment by ericksli** [comment]
@NorbertSandor Please give a try on the latest version `2.0.0`, thanks
