### ISSUE TITLE
Support kotlinx.serialization

### ISSUE THREAD

**Issue by NorbertSandor** [swiftzer/semver#16]
... and annotate `SemVer` with `@Serializable`.

**Comment by ericksli** [comment]
Will consider supporting kotlinx serialization but it should be serialized as a single string, not an object with multiple fields. This can ensure the compatibility in case Kotlin standard library really ships with multiplatform `BigDecimal` and `BigInt` classes in future.

**Comment by ericksli** [comment]
@NorbertSandor Please give a try on the latest version `2.0.0`, thanks
