### ISSUE TITLE
No POM File Published for version 1.1.0

### ISSUE THREAD

**Issue by JLLeitschuh** [swiftzer/semver#2]
Related issues:
https://github.com/gradle/gradle/issues/7584
https://github.com/JLLeitschuh/ktlint-gradle/issues/162

Compare these two releases:
https://bintray.com/swiftzer/maven/semver/1.0.0#files
https://bintray.com/swiftzer/maven/semver/1.1.0#files

![screen shot 2018-11-14 at 5 11 15 pm](https://user-images.githubusercontent.com/1323708/48516037-624ba900-e830-11e8-9fee-251b604a3024.png)
![screen shot 2018-11-14 at 5 11 39 pm](https://user-images.githubusercontent.com/1323708/48516041-64ae0300-e830-11e8-9ba1-66ced147ead2.png)

Somehow, version `1.1.0` is missing a pom file.

CC: @oehme

**Comment by ericksli** [comment]
It is included in the new release 1.1.1:

https://bintray.com/swiftzer/maven/semver/1.1.1

But the POM file does not contain the kotlin standard library dependency. Is that okay?

**Comment by JLLeitschuh** [comment]
In a Kotlin project. Probably fine. As long as this library doesn't have a minimum or maximum standard library that it supports.

**Comment by ericksli** [comment]
Right now migrated to maven central, I think this should be fixed.
