### ISSUE TITLE
Convert to multiplatform project

### ISSUE THREAD

**Issue by NorbertSandor** [swiftzer/semver#5]
Works as a multiplatform implementation with trivial modifications ;)

**Comment by felixbaral** [comment]
Have you already done it? Otherwise I'd give it a shot. I do need that at the moment :)

**Comment by NorbertSandor** [comment]
Sorry, no. (At least not in a "nice" way...)

**Comment by ericksli** [comment]
@felixbaral Hello! I am working on this now and also do a rewrite as well.

**Comment by felixbaral** [comment]
Nice to hear. I did a minimal solution. It works for me, but I ignored dokka and i only tested it on android and ios.

but maybe it is useful
https://github.com/HVN11/semver

**Comment by ericksli** [comment]
@felixbaral I revised the implementation and converted the whole project into a Kotlin mulitplatform project (in `multiplatform` branch). However, I found that running unit tests on NodeJS failed perhaps due to the [regular expression "or" bug in Kotlin/JS](https://youtrack.jetbrains.com/issue/KT-49065)

**Comment by ericksli** [comment]
@NorbertSandor you may take a look on `multiplatform` branch and I have already adoped this approach.

However, I still need some time to migrate the CI to GitHub Actions.

https://github.com/swiftzer/semver/tree/multiplatform

**Comment by ericksli** [comment]
Right now the code in `multiplatform` branch is migrated to Kotlin multiplatform and right now the missing part is the GitHub Actions part

**Comment by ericksli** [comment]
@NorbertSandor @felixbaral Please give a try on the latest version `2.0.0`, thanks

**Comment by felixbaral** [comment]
I tested the `2.0.0` and it works nicely on my ios and android projects
