### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by steffandroid** [swiftzer/semver#8]
[JFrog](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) has just announced that it will be shutting down JCenter on May 1st. JCenter is the sole repository hosting this library, so it will become unavailable after this date unless migrated to an alternative service.

**Comment by ericksli** [comment]
Just migrated to maven central, please check:

https://repo1.maven.org/maven2/net/swiftzer/semver/semver/

**Comment by Tapchicoma** [comment]
Awesome, thank you :+1:
